server: 
  port: 9704
spring: 
  data: 
    mongodb: 
      uri: ${MONGODB_URI}
      database: Ascend
  mail: 
    host: smtp.gmail.com
    port: 587
    username: ${SENDER_EMAIL}
    password: ${SENDER_PASSWORD}
    properties: 
      mail:  
        smtp: 
          auth: true
          starttls:
            enable: true
logging: 
  level: 
    org: 
      springframework: 
        web:  INFO